authors:
  khanh:
    name: Khanh N. Dang
    description: PI
    avatar: https://github.com/khanhdang.png
  6b6c6162:
    name: 6b6c6162
    description: Bot
    avatar: https://github.com/6b6c6162.png
  4b4c4142:
    name: 4b4c4142
    description: Bot
    avatar: https://github.com/4b4c4142.png